
version: '3.9'

services:
  blog-data-db:
    image: postgres:12.17-alpine
    platform: linux/amd64
    container_name: blog-db
    environment:
      POSTGRES_DB: blog-db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - blog-db-data:/var/lib/postgresql/data

volumes:
  blog-db-data:
